apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  namespace: psql-tuning
  name: jupyterlab
spec:
  replicas: 1
  selector: 
    name: jupyterlab
  template:
    metadata:
      labels: 
        name: jupyterlab
    spec:
      containers:
        - name: jupyterlab
          image: ' '
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: postgresql
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: postgresql
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: postgresql
            - name: POSTGRESQL_HOSTNAME
              value: postgresql.psql-tuning
          ports:
            - containerPort: 8888
              protocol: TCP
          restartPolicy: Always
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - jupyterlab
        from:
          kind: ImageStreamTag
          name: psql-tuning:latest
          namespace: psql-tuning
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
  strategy:
    type: Recreate
