apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  namespace: psql-tuning
  name: jupyterlab
spec:
  replicas: 1
  maxUnavailable: 0
  selector:
    name: jupyterlab
  template:
    metadata:
      labels:
        name: jupyterlab
    spec:
      containers:
        - name: jupyterlab
          image: " "
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /lab
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: postgresql
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: postgresql
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: postgresql
            - name: POSTGRESQL_HOSTNAME
              value: postgresql.psql-tuning
          ports:
            - containerPort: 8888
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgresql-data
          restartPolicy: Always
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - jupyterlab
        from:
          kind: ImageStreamTag
          name: psql-tuning:latest
          namespace: psql-tuning
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
  strategy:
    type: Rolling

---
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
spec:
  ports:
    - name: jupyterlab
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    name: jupyterlab
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: jupyter-route
  namespace: psql-tuning
spec:
  host: jupyter-route-psql-tuning.apps-crc.testing
  to:
    kind: Service
    name: jupyterlab
    weight: 100
  port:
    targetPort: jupyterlab
  wildcardPolicy: None
status:
  ingress:
    - host: jupyter-route-psql-tuning.apps-crc.testing
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
      wildcardPolicy: None
