apiVersion: v1
kind: Pod 
metadata:
  labels:
    name: pgbench
  name: pgbench
  namespace: psql-tuning
spec:
  containers:
    - image:  registry.connect.redhat.com/crunchydata/crunchy-pgbench
      name: pgbench-pod
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: "RuntimeDefault"
        capabilities: 
          drop: 
            - ALL
        privileged: false
        runAsNonRoot: true
      env:
      - name: PG_DATABASE
        valueFrom:
          secretKeyRef:
            name: postgresql
            key: database-name
      - name: PG_USERNAME
        valueFrom:
          secretKeyRef:
            name: postgresql
            key: database-user
      - name: PG_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql
            key: database-password
      - name: PG_HOSTNAME
        value: postgresql.psql-tuning
  restartPolicy: OnFailure
status: {}
